import { City } from './city';

export const CITIES: City[] = [
    { id: 1, name: "Istanbul", country: "Turkey", population: 14804116, flag: "../assets/images/flags/Turkey.png" },
    { id: 2, name: "Moscow", country: "Russia", population: 13197596, flag: "../assets/images/flags/Russia.png" },
    { id: 3, name: "London", country: "United Kingdom", population: 8673713, flag: "../assets/images/flags/United_Kingdom.png" },
    { id: 4, name: "Saint Petersburg", country: "Russia", population: 5323300, flag: "../assets/images/flags/Russia.png" },
    { id: 5, name: "Berlin", country: "Germany", population: 3671000, flag: "../assets/images/flags/Germany.png" },
    { id: 6, name: "Madrid", country: "Spain", population: 3165235, flag: "../assets/images/flags/Spain.png" },
    { id: 7, name: "Kiev", country: "Ukraine", population: 2909491, flag: "../assets/images/flags/Ukraine.png" },
    { id: 8, name: "Rome", country: "Italy", population: 2874038, flag: "../assets/images/flags/Italy.png" },
    { id: 9, name: "Paris", country: "France", population: 2241346, flag: "../assets/images/flags/France.png" },
    { id: 10, name: "Minsk", country: "Belarus", population: 1949400, flag: "../assets/images/flags/Turkey.png" },
    { id: 11, name: "Bucharest", country: "Romania", population: 1883144, flag: "../assets/images/flags/Romania.png" },
    { id: 12, name: "Vienna", country: "Austria", population: 1877836, flag: "../assets/images/flags/Austria.png" },
    { id: 13, name: "Budapest", country: "Hungary", population: 1759407, flag: "../assets/images/flags/Hungary.png" },
    { id: 14, name: "Hamburg", country: "Germany", population: 1758041, flag: "../assets/images/flags/Germany.png" },
    { id: 15, name: "Warsaw", country: "Poland", population: 1748916, flag: "../assets/images/flags/Poland.png" },
    { id: 16, name: "Barcelona", country: "Spain", population: 1602386, flag: "../assets/images/flags/Spain.png" },
    { id: 17, name: "Munich", country: "Germany", population: 1521678, flag: "../assets/images/flags/Germany.png" },
    { id: 18, name: "Kharkiv", country: "Ukraine", population: 1431565, flag: "../assets/images/flags/Ukraine.png" },
    { id: 19, name: "Milan", country: "Italy", population: 1351562, flag: "../assets/images/flags/Italy.png" },
    { id: 20, name: "Prague", country: "Czech Republic", population: 1280208, flag: "../assets/images/flags/Czech_Republic.png" },
    { id: 21, name: "Sofia", country: "Bulgaria", population: 1260120, flag: "../assets/images/flags/Bulgaria.png" },
    { id: 22, name: "Nizhny Novgorod", country: "Russia", population: 1250000, flag: "../assets/images/flags/Russia.png" },
    { id: 23, name: "Kazan", country: "Russia", population: 1216965, flag: "../assets/images/flags/Russia.png" },
    { id: 24, name: "Brussels", country: "Belgium", population: 1171828, flag: "../assets/images/flags/Belgium.png" },
    { id: 25, name: "Samara", country: "	Russia", population: 1170910, flag: "../assets/images/flags/Russia.png" },
    { id: 26, name: "Belgrade", country: "Serbia", population: 1166763, flag: "../assets/images/flags/Serbia.png" },
    { id: 27, name: "Rostov-on-Don", country: "Russia", population: 1119875, flag: "../assets/images/flags/Russia.png" },
    { id: 28, name: "Tbilisi", country: "Georgia", population: 1118035, flag: "../assets/images/flags/Georgia.png" },
    { id: 29, name: "Birmingham", country: "United Kingdom", population: 1111300, flag: "../assets/images/flags/United_Kingdom.png" },
    { id: 30, name: "Ufa", country: "Russia", population: 1121429, flag: "../assets/images/flags/Russia.png" },
    { id: 31, name: "Cologne", country: "Germany", population: 1039488, flag: "../assets/images/flags/Germany.png" },
    { id: 32, name: "Perm", country: "Russia", population: 1041876, flag: "../assets/images/flags/Russia.png" },
    { id: 33, name: "Voronezh", country: "Russia", population: 1032382, flag: "../assets/images/flags/Russia.png" },
    { id: 34, name: "Volgograd", country: "Russia", population: 1016137, flag: "../assets/images/flags/Russia.png" },
    { id: 35, name: "Odessa", country: "Ukraine", population: 999359, flag: "../assets/images/flags/Ukraine.png" },
    { id: 36, name: "Dnipro", country: "Ukraine", population: 982969, flag: "../assets/images/flags/Ukraine.png" },
    { id: 37, name: "Naples", country: "Italy", population: 970185, flag: "../assets/images/flags/Italy.png" }
]